import type { SVGProps } from "react";
import {
  ArrowRight,
  ArrowLeft,
  Check,
  CircleCheckBig,
  CircleHelp,
  Clock3,
  ExternalLink,
  Goal,
  Database,
  Eye,
  Info,
  Layers3,
  LockKeyhole,
  Minus,
  Monitor,
  Play,
  Radio,
  RefreshCw,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Trophy,
  Target,
  Users,
  WalletCards,
  WandSparkles,
  Zap,
} from "lucide-react";

const icons = {
  arrow: ArrowRight,
  "arrow-left": ArrowLeft,
  bolt: Zap,
  check: Check,
  "circle-check": CircleCheckBig,
  clock: Clock3,
  database: Database,
  eye: Eye,
  external: ExternalLink,
  goal: Goal,
  help: CircleHelp,
  info: Info,
  layers: Layers3,
  lock: LockKeyhole,
  minus: Minus,
  monitor: Monitor,
  play: Play,
  radio: Radio,
  refresh: RefreshCw,
  shield: ShieldCheck,
  spark: Sparkles,
  smartphone: Smartphone,
  trophy: Trophy,
  target: Target,
  users: Users,
  wallet: WalletCards,
  wand: WandSparkles,
};

export function Icon({ name, ...props }: SVGProps<SVGSVGElement> & { name: string }) {
  const Component = icons[name as keyof typeof icons] ?? CircleHelp;
  return <Component aria-hidden="true" {...props} />;
}
